import os
# def photo():
#  i = 2
#  for file in os.listdir("C:\\Users\DELL\PycharmProjects\pythonProject\Booklist\\"):
#   if file.endswith(".jpg"):
#    src = "C:\\Users\DELL\PycharmProjects\pythonProject\Booklist\\"+file
#    dst = str(i) + ".jpg"
#    dst ="C:\\Users\DELL\PycharmProjects\pythonProject\Booklist\\"+dst
#    os.rename(src, dst)
#    i += 2
#    print("Successfully Done")
print(os.getcwd())