i=1
j=1
k=1
l=1
m=1
while(i!=0):
    while(j!=0):
        while (k!=0):
            while (l!=0):
                while (m!=0):
                    print(i*"A")
                    print(i*"A",end="")
                    print(j*"B")
                    print(i*"A",end="")
                    print(j*"B",end="")
                    print(k*"C")
                    print(i * "A", end="")
                    print(j * "B", end="")
                    print(k*"C",end="")
                    print(l*"D")
                    print(i * "A", end="")
                    print(j * "B", end="")
                    print(k * "C", end="")
                    print(l * "D", end="")
                    print(m*"E")
                    i-= 1
                    j-= 1
                    k-= 1
                    l-= 1
                    m-= 1


