# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'afridip1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tr1 = QtWidgets.QLabel(self.centralwidget)
        self.tr1.setGeometry(QtCore.QRect(170, 110, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr1.setFont(font)
        self.tr1.setStyleSheet("\n"
"color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px")
        self.tr1.setText("")
        self.tr1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tr1.setObjectName("tr1")
        self.tr2 = QtWidgets.QLabel(self.centralwidget)
        self.tr2.setGeometry(QtCore.QRect(170, 150, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr2.setFont(font)
        self.tr2.setStyleSheet("color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px")
        self.tr2.setText("")
        self.tr2.setObjectName("tr2")
        self.tr3 = QtWidgets.QLabel(self.centralwidget)
        self.tr3.setGeometry(QtCore.QRect(170, 190, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr3.setFont(font)
        self.tr3.setStyleSheet("color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px\n"
"")
        self.tr3.setText("")
        self.tr3.setObjectName("tr3")
        self.tr4 = QtWidgets.QLabel(self.centralwidget)
        self.tr4.setGeometry(QtCore.QRect(170, 230, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr4.setFont(font)
        self.tr4.setStyleSheet("color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px")
        self.tr4.setText("")
        self.tr4.setObjectName("tr4")
        self.tr5 = QtWidgets.QLabel(self.centralwidget)
        self.tr5.setGeometry(QtCore.QRect(170, 270, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr5.setFont(font)
        self.tr5.setStyleSheet("color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px")
        self.tr5.setText("")
        self.tr5.setObjectName("tr5")
        self.tr6 = QtWidgets.QLabel(self.centralwidget)
        self.tr6.setGeometry(QtCore.QRect(170, 310, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr6.setFont(font)
        self.tr6.setStyleSheet("color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px")
        self.tr6.setText("")
        self.tr6.setObjectName("tr6")
        self.cn = QtWidgets.QLabel(self.centralwidget)
        self.cn.setGeometry(QtCore.QRect(170, 70, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cn.setFont(font)
        self.cn.setStyleSheet("color:#ca0508;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:3px;\n"
"border-radius:6px")
        self.cn.setText("")
        self.cn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cn.setObjectName("cn")
        self.turnon = QtWidgets.QPushButton(self.centralwidget)
        self.turnon.setGeometry(QtCore.QRect(320, 520, 711, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.turnon.setFont(font)
        self.turnon.setStyleSheet("background-color:rgb(0, 170, 0);\n"
"border-color::rgb(0, 170, 0);\n"
"border-width:5px;\n"
"border-radius:8px;\n"
"color:white;")
        self.turnon.setObjectName("turnon")
        self.dc = QtWidgets.QLabel(self.centralwidget)
        self.dc.setGeometry(QtCore.QRect(170, 20, 1021, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dc.setFont(font)
        self.dc.setStyleSheet("color:#ca0508;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:4px;\n"
"border-radius:8px")
        self.dc.setText("")
        self.dc.setAlignment(QtCore.Qt.AlignCenter)
        self.dc.setObjectName("dc")
        self.tr7 = QtWidgets.QLabel(self.centralwidget)
        self.tr7.setGeometry(QtCore.QRect(170, 350, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr7.setFont(font)
        self.tr7.setStyleSheet("color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px")
        self.tr7.setText("")
        self.tr7.setObjectName("tr7")
        self.tr9 = QtWidgets.QLabel(self.centralwidget)
        self.tr9.setGeometry(QtCore.QRect(170, 430, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr9.setFont(font)
        self.tr9.setStyleSheet("color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px")
        self.tr9.setText("")
        self.tr9.setObjectName("tr9")
        self.tr10 = QtWidgets.QLabel(self.centralwidget)
        self.tr10.setGeometry(QtCore.QRect(170, 470, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr10.setFont(font)
        self.tr10.setStyleSheet("color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px")
        self.tr10.setText("")
        self.tr10.setObjectName("tr10")
        self.tr8 = QtWidgets.QLabel(self.centralwidget)
        self.tr8.setGeometry(QtCore.QRect(170, 390, 1021, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tr8.setFont(font)
        self.tr8.setStyleSheet("color:white;\n"
"background-color:#191919;\n"
"border-style:outset;\n"
"border-color:#aa0000;\n"
"border-width:2px;\n"
"border-radius:5px")
        self.tr8.setText("")
        self.tr8.setObjectName("tr8")
        self.tn0 = QtWidgets.QLabel(self.centralwidget)
        self.tn0.setGeometry(QtCore.QRect(170, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn0.setFont(font)
        self.tn0.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn0.setText("")
        self.tn0.setAlignment(QtCore.Qt.AlignCenter)
        self.tn0.setObjectName("tn0")
        self.at = QtWidgets.QLabel(self.centralwidget)
        self.at.setGeometry(QtCore.QRect(750, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at.setFont(font)
        self.at.setStyleSheet("color:white;\n"
"\n"
"")
        self.at.setText("")
        self.at.setAlignment(QtCore.Qt.AlignCenter)
        self.at.setObjectName("at")
        self.tname0 = QtWidgets.QLabel(self.centralwidget)
        self.tname0.setGeometry(QtCore.QRect(310, 110, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname0.setFont(font)
        self.tname0.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname0.setText("")
        self.tname0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname0.setObjectName("tname0")
        self.tn1 = QtWidgets.QLabel(self.centralwidget)
        self.tn1.setGeometry(QtCore.QRect(170, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn1.setFont(font)
        self.tn1.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn1.setText("")
        self.tn1.setAlignment(QtCore.Qt.AlignCenter)
        self.tn1.setObjectName("tn1")
        self.tn2 = QtWidgets.QLabel(self.centralwidget)
        self.tn2.setGeometry(QtCore.QRect(170, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn2.setFont(font)
        self.tn2.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn2.setText("")
        self.tn2.setAlignment(QtCore.Qt.AlignCenter)
        self.tn2.setObjectName("tn2")
        self.tn3 = QtWidgets.QLabel(self.centralwidget)
        self.tn3.setGeometry(QtCore.QRect(170, 230, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn3.setFont(font)
        self.tn3.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn3.setText("")
        self.tn3.setAlignment(QtCore.Qt.AlignCenter)
        self.tn3.setObjectName("tn3")
        self.tn4 = QtWidgets.QLabel(self.centralwidget)
        self.tn4.setGeometry(QtCore.QRect(170, 270, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn4.setFont(font)
        self.tn4.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn4.setText("")
        self.tn4.setAlignment(QtCore.Qt.AlignCenter)
        self.tn4.setObjectName("tn4")
        self.tn5 = QtWidgets.QLabel(self.centralwidget)
        self.tn5.setGeometry(QtCore.QRect(170, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn5.setFont(font)
        self.tn5.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn5.setText("")
        self.tn5.setAlignment(QtCore.Qt.AlignCenter)
        self.tn5.setObjectName("tn5")
        self.tn6 = QtWidgets.QLabel(self.centralwidget)
        self.tn6.setGeometry(QtCore.QRect(170, 350, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn6.setFont(font)
        self.tn6.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn6.setText("")
        self.tn6.setAlignment(QtCore.Qt.AlignCenter)
        self.tn6.setObjectName("tn6")
        self.tn7 = QtWidgets.QLabel(self.centralwidget)
        self.tn7.setGeometry(QtCore.QRect(170, 390, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn7.setFont(font)
        self.tn7.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn7.setText("")
        self.tn7.setAlignment(QtCore.Qt.AlignCenter)
        self.tn7.setObjectName("tn7")
        self.tn8 = QtWidgets.QLabel(self.centralwidget)
        self.tn8.setGeometry(QtCore.QRect(170, 430, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn8.setFont(font)
        self.tn8.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn8.setText("")
        self.tn8.setAlignment(QtCore.Qt.AlignCenter)
        self.tn8.setObjectName("tn8")
        self.tn9 = QtWidgets.QLabel(self.centralwidget)
        self.tn9.setGeometry(QtCore.QRect(170, 470, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn9.setFont(font)
        self.tn9.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn9.setText("")
        self.tn9.setAlignment(QtCore.Qt.AlignCenter)
        self.tn9.setObjectName("tn9")
        self.tn = QtWidgets.QLabel(self.centralwidget)
        self.tn.setGeometry(QtCore.QRect(170, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tn.setFont(font)
        self.tn.setStyleSheet("color:white;\n"
"\n"
"")
        self.tn.setText("")
        self.tn.setAlignment(QtCore.Qt.AlignCenter)
        self.tn.setObjectName("tn")
        self.tname = QtWidgets.QLabel(self.centralwidget)
        self.tname.setGeometry(QtCore.QRect(310, 70, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname.setFont(font)
        self.tname.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname.setText("")
        self.tname.setAlignment(QtCore.Qt.AlignCenter)
        self.tname.setObjectName("tname")
        self.tname1 = QtWidgets.QLabel(self.centralwidget)
        self.tname1.setGeometry(QtCore.QRect(310, 150, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname1.setFont(font)
        self.tname1.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname1.setText("")
        self.tname1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname1.setObjectName("tname1")
        self.tname2 = QtWidgets.QLabel(self.centralwidget)
        self.tname2.setGeometry(QtCore.QRect(310, 190, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname2.setFont(font)
        self.tname2.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname2.setText("")
        self.tname2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname2.setObjectName("tname2")
        self.tname3 = QtWidgets.QLabel(self.centralwidget)
        self.tname3.setGeometry(QtCore.QRect(310, 230, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname3.setFont(font)
        self.tname3.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname3.setText("")
        self.tname3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname3.setObjectName("tname3")
        self.tname4 = QtWidgets.QLabel(self.centralwidget)
        self.tname4.setGeometry(QtCore.QRect(310, 270, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname4.setFont(font)
        self.tname4.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname4.setText("")
        self.tname4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname4.setObjectName("tname4")
        self.tname5 = QtWidgets.QLabel(self.centralwidget)
        self.tname5.setGeometry(QtCore.QRect(310, 310, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname5.setFont(font)
        self.tname5.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname5.setText("")
        self.tname5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname5.setObjectName("tname5")
        self.tname6 = QtWidgets.QLabel(self.centralwidget)
        self.tname6.setGeometry(QtCore.QRect(310, 350, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname6.setFont(font)
        self.tname6.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname6.setText("")
        self.tname6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname6.setObjectName("tname6")
        self.tname7 = QtWidgets.QLabel(self.centralwidget)
        self.tname7.setGeometry(QtCore.QRect(310, 390, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname7.setFont(font)
        self.tname7.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname7.setText("")
        self.tname7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname7.setObjectName("tname7")
        self.tname8 = QtWidgets.QLabel(self.centralwidget)
        self.tname8.setGeometry(QtCore.QRect(310, 430, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname8.setFont(font)
        self.tname8.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname8.setText("")
        self.tname8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname8.setObjectName("tname8")
        self.tname9 = QtWidgets.QLabel(self.centralwidget)
        self.tname9.setGeometry(QtCore.QRect(310, 470, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tname9.setFont(font)
        self.tname9.setStyleSheet("color:white;\n"
"\n"
"")
        self.tname9.setText("")
        self.tname9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tname9.setObjectName("tname9")
        self.dt = QtWidgets.QLabel(self.centralwidget)
        self.dt.setGeometry(QtCore.QRect(890, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt.setFont(font)
        self.dt.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt.setText("")
        self.dt.setAlignment(QtCore.Qt.AlignCenter)
        self.dt.setObjectName("dt")
        self.pt = QtWidgets.QLabel(self.centralwidget)
        self.pt.setGeometry(QtCore.QRect(1050, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt.setFont(font)
        self.pt.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt.setText("")
        self.pt.setAlignment(QtCore.Qt.AlignCenter)
        self.pt.setObjectName("pt")
        self.at0 = QtWidgets.QLabel(self.centralwidget)
        self.at0.setGeometry(QtCore.QRect(750, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at0.setFont(font)
        self.at0.setStyleSheet("color:white;\n"
"\n"
"")
        self.at0.setText("")
        self.at0.setAlignment(QtCore.Qt.AlignCenter)
        self.at0.setObjectName("at0")
        self.at1 = QtWidgets.QLabel(self.centralwidget)
        self.at1.setGeometry(QtCore.QRect(750, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at1.setFont(font)
        self.at1.setStyleSheet("color:white;\n"
"\n"
"")
        self.at1.setText("")
        self.at1.setAlignment(QtCore.Qt.AlignCenter)
        self.at1.setObjectName("at1")
        self.at2 = QtWidgets.QLabel(self.centralwidget)
        self.at2.setGeometry(QtCore.QRect(750, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at2.setFont(font)
        self.at2.setStyleSheet("color:white;\n"
"\n"
"")
        self.at2.setText("")
        self.at2.setAlignment(QtCore.Qt.AlignCenter)
        self.at2.setObjectName("at2")
        self.at3 = QtWidgets.QLabel(self.centralwidget)
        self.at3.setGeometry(QtCore.QRect(750, 230, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at3.setFont(font)
        self.at3.setStyleSheet("color:white;\n"
"\n"
"")
        self.at3.setText("")
        self.at3.setAlignment(QtCore.Qt.AlignCenter)
        self.at3.setObjectName("at3")
        self.at4 = QtWidgets.QLabel(self.centralwidget)
        self.at4.setGeometry(QtCore.QRect(750, 270, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at4.setFont(font)
        self.at4.setStyleSheet("color:white;\n"
"\n"
"")
        self.at4.setText("")
        self.at4.setAlignment(QtCore.Qt.AlignCenter)
        self.at4.setObjectName("at4")
        self.at5 = QtWidgets.QLabel(self.centralwidget)
        self.at5.setGeometry(QtCore.QRect(750, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at5.setFont(font)
        self.at5.setStyleSheet("color:white;\n"
"\n"
"")
        self.at5.setText("")
        self.at5.setAlignment(QtCore.Qt.AlignCenter)
        self.at5.setObjectName("at5")
        self.at6 = QtWidgets.QLabel(self.centralwidget)
        self.at6.setGeometry(QtCore.QRect(750, 350, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at6.setFont(font)
        self.at6.setStyleSheet("color:white;\n"
"\n"
"")
        self.at6.setText("")
        self.at6.setAlignment(QtCore.Qt.AlignCenter)
        self.at6.setObjectName("at6")
        self.at7 = QtWidgets.QLabel(self.centralwidget)
        self.at7.setGeometry(QtCore.QRect(750, 390, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at7.setFont(font)
        self.at7.setStyleSheet("color:white;\n"
"\n"
"")
        self.at7.setText("")
        self.at7.setAlignment(QtCore.Qt.AlignCenter)
        self.at7.setObjectName("at7")
        self.at8 = QtWidgets.QLabel(self.centralwidget)
        self.at8.setGeometry(QtCore.QRect(750, 430, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at8.setFont(font)
        self.at8.setStyleSheet("color:white;\n"
"\n"
"")
        self.at8.setText("")
        self.at8.setAlignment(QtCore.Qt.AlignCenter)
        self.at8.setObjectName("at8")
        self.at9 = QtWidgets.QLabel(self.centralwidget)
        self.at9.setGeometry(QtCore.QRect(750, 470, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.at9.setFont(font)
        self.at9.setStyleSheet("color:white;\n"
"\n"
"")
        self.at9.setText("")
        self.at9.setAlignment(QtCore.Qt.AlignCenter)
        self.at9.setObjectName("at9")
        self.dt0 = QtWidgets.QLabel(self.centralwidget)
        self.dt0.setGeometry(QtCore.QRect(890, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt0.setFont(font)
        self.dt0.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt0.setText("")
        self.dt0.setAlignment(QtCore.Qt.AlignCenter)
        self.dt0.setObjectName("dt0")
        self.dt1 = QtWidgets.QLabel(self.centralwidget)
        self.dt1.setGeometry(QtCore.QRect(890, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt1.setFont(font)
        self.dt1.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt1.setText("")
        self.dt1.setAlignment(QtCore.Qt.AlignCenter)
        self.dt1.setObjectName("dt1")
        self.dt2 = QtWidgets.QLabel(self.centralwidget)
        self.dt2.setGeometry(QtCore.QRect(890, 190, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt2.setFont(font)
        self.dt2.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt2.setText("")
        self.dt2.setAlignment(QtCore.Qt.AlignCenter)
        self.dt2.setObjectName("dt2")
        self.dt3 = QtWidgets.QLabel(self.centralwidget)
        self.dt3.setGeometry(QtCore.QRect(890, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt3.setFont(font)
        self.dt3.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt3.setText("")
        self.dt3.setAlignment(QtCore.Qt.AlignCenter)
        self.dt3.setObjectName("dt3")
        self.dt4 = QtWidgets.QLabel(self.centralwidget)
        self.dt4.setGeometry(QtCore.QRect(890, 270, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt4.setFont(font)
        self.dt4.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt4.setText("")
        self.dt4.setAlignment(QtCore.Qt.AlignCenter)
        self.dt4.setObjectName("dt4")
        self.dt5 = QtWidgets.QLabel(self.centralwidget)
        self.dt5.setGeometry(QtCore.QRect(890, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt5.setFont(font)
        self.dt5.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt5.setText("")
        self.dt5.setAlignment(QtCore.Qt.AlignCenter)
        self.dt5.setObjectName("dt5")
        self.dt6 = QtWidgets.QLabel(self.centralwidget)
        self.dt6.setGeometry(QtCore.QRect(890, 350, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt6.setFont(font)
        self.dt6.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt6.setText("")
        self.dt6.setAlignment(QtCore.Qt.AlignCenter)
        self.dt6.setObjectName("dt6")
        self.dt7 = QtWidgets.QLabel(self.centralwidget)
        self.dt7.setGeometry(QtCore.QRect(890, 390, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt7.setFont(font)
        self.dt7.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt7.setText("")
        self.dt7.setAlignment(QtCore.Qt.AlignCenter)
        self.dt7.setObjectName("dt7")
        self.dt8 = QtWidgets.QLabel(self.centralwidget)
        self.dt8.setGeometry(QtCore.QRect(890, 430, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt8.setFont(font)
        self.dt8.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt8.setText("")
        self.dt8.setAlignment(QtCore.Qt.AlignCenter)
        self.dt8.setObjectName("dt8")
        self.dt9 = QtWidgets.QLabel(self.centralwidget)
        self.dt9.setGeometry(QtCore.QRect(890, 470, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dt9.setFont(font)
        self.dt9.setStyleSheet("color:white;\n"
"\n"
"")
        self.dt9.setText("")
        self.dt9.setAlignment(QtCore.Qt.AlignCenter)
        self.dt9.setObjectName("dt9")
        self.pt0 = QtWidgets.QLabel(self.centralwidget)
        self.pt0.setGeometry(QtCore.QRect(1050, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt0.setFont(font)
        self.pt0.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt0.setText("")
        self.pt0.setAlignment(QtCore.Qt.AlignCenter)
        self.pt0.setObjectName("pt0")
        self.pt1 = QtWidgets.QLabel(self.centralwidget)
        self.pt1.setGeometry(QtCore.QRect(1050, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt1.setFont(font)
        self.pt1.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt1.setText("")
        self.pt1.setAlignment(QtCore.Qt.AlignCenter)
        self.pt1.setObjectName("pt1")
        self.pt2 = QtWidgets.QLabel(self.centralwidget)
        self.pt2.setGeometry(QtCore.QRect(1050, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt2.setFont(font)
        self.pt2.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt2.setText("")
        self.pt2.setAlignment(QtCore.Qt.AlignCenter)
        self.pt2.setObjectName("pt2")
        self.pt3 = QtWidgets.QLabel(self.centralwidget)
        self.pt3.setGeometry(QtCore.QRect(1050, 230, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt3.setFont(font)
        self.pt3.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt3.setText("")
        self.pt3.setAlignment(QtCore.Qt.AlignCenter)
        self.pt3.setObjectName("pt3")
        self.pt4 = QtWidgets.QLabel(self.centralwidget)
        self.pt4.setGeometry(QtCore.QRect(1050, 270, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt4.setFont(font)
        self.pt4.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt4.setText("")
        self.pt4.setAlignment(QtCore.Qt.AlignCenter)
        self.pt4.setObjectName("pt4")
        self.pt5 = QtWidgets.QLabel(self.centralwidget)
        self.pt5.setGeometry(QtCore.QRect(1050, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt5.setFont(font)
        self.pt5.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt5.setText("")
        self.pt5.setAlignment(QtCore.Qt.AlignCenter)
        self.pt5.setObjectName("pt5")
        self.pt6 = QtWidgets.QLabel(self.centralwidget)
        self.pt6.setGeometry(QtCore.QRect(1050, 350, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt6.setFont(font)
        self.pt6.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt6.setText("")
        self.pt6.setAlignment(QtCore.Qt.AlignCenter)
        self.pt6.setObjectName("pt6")
        self.pt7 = QtWidgets.QLabel(self.centralwidget)
        self.pt7.setGeometry(QtCore.QRect(1050, 390, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt7.setFont(font)
        self.pt7.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt7.setText("")
        self.pt7.setAlignment(QtCore.Qt.AlignCenter)
        self.pt7.setObjectName("pt7")
        self.pt8 = QtWidgets.QLabel(self.centralwidget)
        self.pt8.setGeometry(QtCore.QRect(1050, 430, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt8.setFont(font)
        self.pt8.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt8.setText("")
        self.pt8.setAlignment(QtCore.Qt.AlignCenter)
        self.pt8.setObjectName("pt8")
        self.pt9 = QtWidgets.QLabel(self.centralwidget)
        self.pt9.setGeometry(QtCore.QRect(1050, 470, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pt9.setFont(font)
        self.pt9.setStyleSheet("color:white;\n"
"\n"
"")
        self.pt9.setText("")
        self.pt9.setAlignment(QtCore.Qt.AlignCenter)
        self.pt9.setObjectName("pt9")
        self.status = QtWidgets.QPushButton(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(320, 580, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setStyleSheet("background-color:rgb(216, 0, 0);\n"
"border-color::rgb(0, 170, 0);\n"
"border-width:5px;\n"
"border-radius:8px;\n"
"color:white;")
        self.status.setObjectName("status")
        self.location = QtWidgets.QPushButton(self.centralwidget)
        self.location.setGeometry(QtCore.QRect(690, 580, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.location.setFont(font)
        self.location.setStyleSheet("background-color:rgb(0, 0, 186);\n"
"border-color::rgb(0, 170, 0);\n"
"border-width:5px;\n"
"border-radius:8px;\n"
"color:white;")
        self.location.setObjectName("location")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1051, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.turnon.setText(_translate("MainWindow", "UPDATE"))
        self.status.setText(_translate("MainWindow", "CHECK LIVE TRAIN STATUS"))
        self.location.setText(_translate("MainWindow", "CHECK LIVE TRAIN LOCATION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
