# Generated by Django 3.1.3 on 2021-06-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qn_No', models.IntegerField(max_length=10)),
                ('Question', models.CharField(max_length=1000)),
                ('Option_A', models.CharField(max_length=1000)),
                ('Option_B', models.CharField(max_length=1000)),
                ('Option_C', models.CharField(max_length=1000)),
                ('Option_D', models.CharField(max_length=1000)),
                ('Answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
